services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\Web2PrintToolsBundle\Twig\OutputChannelExtension:
        tags: ['twig.extension']


    Pimcore\Bundle\Web2PrintToolsBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']


    Pimcore\Bundle\Web2PrintToolsBundle\Tools\Installer:
        public: true
        arguments:
            # fetch the bundle via expression language
            $bundle: "@=service('kernel').getBundle('Web2PrintToolsBundle')"